/*      File Name                Flash Index                   */
/*      ---------                -----------                   */
#define Start_preCache             0x20  /* File Size = 0xCC   */
#define Start                      0x21  /* File Size = 0xB0   */
#define Game                       0x22  /* File Size = 0x594C */
#define GameOver                   0x23  /* File Size = 0x110  */
/*      GameOver_272x480.png       0x24  /* File Size = 0x8D4E */
/*      PCBoardBack_272x480.png    0x25  /* File Size = 0x83AA */
/*      StartMenu_272x480.png      0x26  /* File Size = 0x84A2 */
/*      Amulet.pal                 0x27  /* File Size = 0x406  */
/*      StartButton1_219x75.png    0x28  /* File Size = 0x1632 */
/*      StartButton2_219x75.png    0x29  /* File Size = 0x14A2 */
/*      Paddle_64x13.png           0x2A  /* File Size = 0x1FA  */
/*      LEDE_51x82.png             0x2B  /* File Size = 0x8D2  */
/*      LED1_51x82.png             0x2C  /* File Size = 0x8C2  */
/*      LED2_51x82.png             0x2D  /* File Size = 0x886  */
/*      LED3_51x82.png             0x2E  /* File Size = 0x87E  */
/*      Resistor0_50x20.png        0x2F  /* File Size = 0x1A2  */
/*      Resistor1_50x20.png        0x30  /* File Size = 0x24E  */
/*      Resistor2_50x20.png        0x31  /* File Size = 0x26A  */
/*      Resistor3_50x20.png        0x32  /* File Size = 0x246  */
/*      Ball2.gif                  0x33  /* File Size = 0x16A  */
/*      GOYes_73x55.png            0x34  /* File Size = 0x62E  */
/*      GONo_60x50.png             0x35  /* File Size = 0x4EE  */
/*      fonthdr.auf                0xF   /* File Size = 0x2E   */
/*      internalram.bin            0x6   /* File Size = 0x2138 */
/*      sdramconfig.bin            0x1   /* File Size = 0x92   */
/*      rttinit.bin                0x1D  /* File Size = 0x12   */
